### ISSUE TITLE
Does this help for spotlight issue?

### ISSUE THREAD

**Issue by schroef** [ruimarinho/little-snitch-rules#1]
I just update my OS and thus LittleSnitch needed an updated. Now I'm getting so annoyed by every hit in spotlight which is a website, I'm going crazy.

Does this repo help solve that?

**Comment by ruimarinho** [comment]
Not as it stands right now, as there is only one domain listed. You can either go the easy route and whitelist everything that is HTTP(S) or disable Spotlight suggestions on system preferences.
